eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    

microservice: 
  ORDER-SERVICE: 
    endpoints: 
      endpoint: 
        uri: "http://ORDER-SERVICE/order/bookorder"
  PAYMENT-SERVICE: 
    endpoints: 
      endpoint: 
        uri: "http://PAYMENT-SERVICE/pay/payment"
     
  CAMUNDA-SERVICE: 
    endpoints: 
      endpoint: 
        uri: "http://CAMUNDA-SERVICE/engine-rest"
