eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    

microservice:
  PAYMENT-SERVICE:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/pay/payment
        
  ORDER-SERVICE:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookorder      
        
